# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69952237c5f4691b0e665e77706ad2313ba354f7d78bce7e1a43be622fbca5fbe292713987c5cfe9a4b7d3ca1f403a82326e8ea2cf8233d3589aef61388848b

test:
  secret_key_base: a0036537a2107b97e163ec3a4710b39ea68f544e8c5400434acf6792e8b16ea0659a887b3a1cc7c1b1c4d8526b91883507135326c0552183d80baf167683c599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
